fix select query without from
vapor/sql-kit pull request #125
Opened 2021-02-22 11:25 UTC by Freax13

Not all `SELECT` queries require a `FROM` statement. This pr fixes the query generation for queries without `FROM` and allows the following example to work:

```swift
conn.sql()
    .select()
    .column(SQLAlias.init(SQLFunction("LAST_INSERT_ID"), as: SQLIdentifier.init("id")))
    .first()
```

2021-03-03 12:50 UTC, gwynne approved these changes
Huh, I coulda sworn I'd already fixed that... guess not. Thanks, looks great!

2021-03-03 12:51 UTC, gwynne requested changes
@Freax13 Sorry, I just realized two seconds before I hit the merge button... Could you add a unit test for this? 😅

2021-03-06 17:01 UTC, gwynne approved these changes

2021-03-06 17:17 UTC, merged

2021-03-06 17:17 UTC, tanner0101 commented
These changes are now available in [3.8.1](https://github.com/vapor/sql-kit/releases/tag/3.8.1)