Adds orWhere methods to match where methods
vapor/sql-kit pull request #130
Opened 2021-05-20 04:02 UTC by NeedleInAJayStack

Adds methods that `where` had but `orWhere` was missing. Specifically, it adds `orWhere` methods for when the right-hand-side is:

* an encodable
* a list of encodables
* a column identifier

For example, before this PR:

```
builder.where("name", .equal, "Earth") // Valid
builder.orWhere("name", .equal, "Earth") // Invalid
```

2021-07-06 01:09 UTC, NeedleInAJayStack commented
Hey @0xTim, you mind doing a quick review on this one too?

2021-07-20 14:10 UTC, 0xTim requested changes
Mostly LGTM - can you add more tests for all the new functions? They currently only cover one of them

2021-07-20 14:10 UTC, 0xTim commented on Sources/SQLKit/Builders/SQLPredicateBuilder.swift
> +    ///     SELECT * FROM planets WHERE name = ? // Earth
The SQL doesn't match the builder function defined above?

2021-07-20 16:25 UTC, NeedleInAJayStack commented
@0xTim Thanks for the review! I've added orWheres to tests and cleaned up the documentation.

2021-07-21 12:39 UTC, 0xTim approved these changes
Thanks!

2021-07-21 12:41 UTC, merged